# Generated by Django 5.2.4 on 2026-06-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fecha_multa', models.DateTimeField(auto_now_add=True)),
                ('pagada', models.BooleanField(default=False)),
            ],
        ),
    ]
