# Generated by Django 5.2.4 on 2026-06-14 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('multas', '0001_initial'),
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='multa',
            name='prestamo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='multa', to='prestamos.prestamo'),
        ),
    ]
